spring:
  application:
    name: ai-service
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
  #        show_sql: true # sql 로깅
  #        format_sql: true # SQL 문 정렬하여 출력
  #        highlight_sql: true # SQL 문 색 부여
  #        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
  #        database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0

server:
  port: 19098

springdoc:
  api-docs:
    enabled: true
    path: /ai-service/v3/api-docs
  swagger-ui:
    path: /ai-service/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}

gemini:
  baseurl: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
  key: ${DEV_GEMINI_KEY}

weather:
  baseurl: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
  key: ${DEV_WEATHER_KEY}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
