spring:
  application:
    name: auth-service
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}

server:
  port: 19100

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: true
    path: /auth-service/v3/api-docs
  swagger-ui:
    path: /auth-service/swagger-ui.html

jwt:
  secret:
    key: ${JWT_SECRET_KEY}