spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19100

jwt:
  secret:
    key: ${JWT_SECRET_KEY}