spring:
  application:
    name: slack-service
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #        database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092



eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

slack:
  url: ${SLACK_WEBHOOK_URL}

server:
  port: 19099
