spring:
  application:
    name: slack-service
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #        database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 19099

springdoc:
  api-docs:
    enabled: true
    path: /slack-service/v3/api-docs
  swagger-ui:
    path: /slack-service/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0

slack:
  url: ${SLACK_WEBHOOK_URL}

