server:
  port: 19091

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service  #인증
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service  # 유저
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: order-service  # 주문
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: delivery-service  # 배송
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/**
        - id: hub-service # 허브
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**
        - id: product-service # 상품
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: company-service # 업체
          uri: lb://company-service
          predicates:
            - Path=/api/v1/companies/**
        - id: ai-service  # AI
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ais/**
        - id: slack-service # slack
          uri: lb://slack-service
          predicates:
            - Path=/api/v1/slacks/**
      discovery:
        locator:
          enabled: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/