spring:
  application:
    name: product-service

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      show_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}

springdoc:
  api-docs:
    enabled: true
    path: /product-service/v3/api-docs
  swagger-ui:
    path: /product-service/swagger-ui.html

server:
  port: 19095

jwt:
  secret:
    key: ${JWT_SECRET_KEY}